name: yak_geofencing_platform_interface
description:
version: 0.0.1
repository: https://github.com/yak-digital/flutter-geofencing/tree/main/geofencing_platform_interface
issue_tracker: https://github.com/yak-digital/flutter-geofencing/issues?q=is%3Aissue+is%3Aopen+label%3A%22yak_geofencing_platform_interface%22

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.8.0
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0